jobs:
  include:

    # If this is a tagged commit, publish the package to npm
    - stage: Release npm
      script: echo "Deploying to npm"
      deploy:
        provider: npm
        email: asyncadventures@gmail.com
        api_key: $NPM_TOKEN
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
